title = "Relevent papers"

end_date = "now"
time_delta = "01:00:00:00"

[summarize]
type = "gpt"
provider = "openai" # or "azure"
model_name = "gpt-3.5-turbo"
# API KEY should be in ENV

[email]
recipients = ["ea_azzoug@esi.dz"]

[teams]
webhook_url = "https://test_webhook.com/test=123xyz"

[local_dir]
path = "./tmp"

[slack]
channel_id = "my-channel"

[[query]]
title = "LLM"
raw_content = """intitle:(GPT* OR ChatGPT OR LLM* OR prompt* OR instruction* OR "Language Models" OR "Large language model" OR "Large language models" OR "generative" OR "All you need" OR instruction*) AND incontent:(result* OR survey OR review OR metric* OR evaluation* OR benchmark* OR SOTA OR PLM* OR prompt* OR gpt* OR experiment* OR optimization* OR distillation*)"""

[[query]]
title = "Doc Aug"
raw_content = "intitle:(generation OR augmentation) AND incontent:(document*)"

[[query]]
title = "AL"
raw_content = """intitle:("active learning") AND incontent:(VRD OR documents OR extraction OR detection OR survey* OR benchmark*)"""

[[source]]
type = "arxiv"
use_abstract_as_content = true
search_topic = "cs"
max_documents = 400

[[source]]
type = "openai_blog"
max_documents = 20

[[source]]
type = "techcrunch"
search_topic = "category/artificial-intelligence/"
max_documents = 50
